server:
  port: 8091
  ssl:
    key-store: classpath:cert/cert-2408076956bd1a5a1ee75f_www.wenkaiyu.top_TOMCAT.pfx
    key-store-password: k75d67Ad2LHe2229
    key-store-type: PKCS12  #证书类型
    enabled: true



spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: https://www.wenkaiyu.top:8123
          predicates:
            - Path=/api/**

      default-filters:
        - AddRequestHeader=source, kyapi
logging:
  root:
    level:
      org:
        springframework:
          cloud:
            gateway:trace


dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-provider
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22224
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://172.16.0.3:8848
